name: chatly
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.2
  cloud_firestore: any
  firebase_auth: any
  firebase_core: any
  firebase_storage: ^3.1.5


  image_picker: ^0.6.6+1
  modal_progress_hud: ^0.1.3
  cached_network_image: ^2.1.0+1

  shared_preferences: ^0.5.7+1

  flutter_app_badger: ^1.1.2
  flutter_widgets: ^0.1.7+1

  photo_view: ^0.9.2
  font_awesome_flutter: any



dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:


  uses-material-design: true
